version: '3.8' # или более поздняя версия

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aks124alv124
      POSTGRES_DB: employees_db_new
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: